# Generated by Django 5.1.2 on 2024-11-28 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instituicao_participante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='estado',
            new_name='estado_instituicao',
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='nome',
            new_name='instituicao_nome',
        ),
        migrations.AddField(
            model_name='instituicao',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
