# Generated by Django 5.1.2 on 2024-12-04 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_estado_instituicao_estado_instituicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='estado_instituicao',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='nome_instituicao',
        ),
        migrations.AddField(
            model_name='participante',
            name='estado_participante',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='BA', max_length=2),
        ),
        migrations.AddField(
            model_name='participante',
            name='formacao_participante',
            field=models.CharField(choices=[('Fundamental - Incompleto', 'Fundamental - Incompleto'), ('Fundamental - Completo', 'Fundamental - Completo'), ('Médio - Incompleto', 'Médio - Incompleto'), ('Médio - Completo', 'Médio - Completo'), ('Superior - Incompleto', 'Superior - Incompleto'), ('Superior - Completo', 'Superior - Completo'), ('Pós-graduação (Lato sensu) - Incompleto', 'Pós-graduação (Lato sensu) - Incompleto'), ('Pós-graduação (Lato sensu) - Completo', 'Pós-graduação (Lato sensu) - Completo'), ('Pós-graduação (Stricto sensu, nível mestrado) - Incompleto', 'Pós-graduação (Stricto sensu, nível mestrado) - Incompleto'), ('Pós-graduação (Stricto sensu, nível mestrado) - Completo', 'Pós-graduação (Stricto sensu, nível mestrado) - Completo'), ('Pós-graduação (Stricto sensu, nível doutor) - Incompleto', 'Pós-graduação (Stricto sensu, nível doutor) - Incompleto'), ('Pós-graduação (Stricto sensu, nível doutor) - Completo', 'Pós-graduação (Stricto sensu, nível doutor) - Completo')], default='Médio - Completo', max_length=60),
        ),
        migrations.AddField(
            model_name='participante',
            name='instituicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participante',
            name='nome_participante',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='estado_instituicao',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='BA', max_length=2),
        ),
    ]
