# Generated by Django 5.1.2 on 2024-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_participante_email_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='instituicao',
        ),
        migrations.AddField(
            model_name='participante',
            name='cep_pacticipante',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
