# Generated by Django 5.1.2 on 2024-12-10 11:54

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_municipio_participante_municipio_participante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('formation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('image', stdimage.models.StdImageField(blank=True, default='photos/default.jpg', force_min_size=False, null=True, upload_to='photos/', variations={})),
            ],
        ),
    ]
