# Generated by Django 5.1.4 on 2025-02-06 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_commission_email_commission_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='email',
            new_name='email_member',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='formation',
            new_name='formation_member',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='image',
            new_name='member_profile',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='name',
            new_name='name_member',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='phone',
            new_name='phone_member',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='position',
        ),
        migrations.AddField(
            model_name='commission',
            name='position_member',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='commission',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_commission', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
