# Generated by Django 5.2.4 on 2025-08-25 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_email_commission_email_member_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposFecitec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='grupos_fecitec', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GrupoPersonalizado',
        ),
    ]
