# Generated by Django 5.2.4 on 2025-08-26 00:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gruposfecitec_delete_grupopersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GruposFecitec',
            new_name='GroupsFecitec',
        ),
        migrations.RenameField(
            model_name='groupsfecitec',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='groupsfecitec',
            old_name='nome',
            new_name='name',
        ),
    ]
