# Generated by Django 5.2.4 on 2025-08-26 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_gruposfecitec_groupsfecitec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupsfecitec',
            old_name='name',
            new_name='namegroup',
        ),
    ]
