# Generated by Django 5.2.4 on 2025-09-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_name_groupsfecitec_namegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontowork',
            name='evaluators',
            field=models.ManyToManyField(blank=True, related_name='trabalhos_avaliados', to='core.commission'),
        ),
    ]
