# Generated by Django 5.2.4 on 2025-09-15 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_submissiontowork_evaluators'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments_at', models.DateTimeField(auto_now_add=True)),
                ('juror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.commission')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.submissiontowork')),
            ],
        ),
    ]
