# Generated by Django 5.1.2 on 2024-11-01 13:52

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='fecitec/static/images', variations={}),
        ),
    ]
