# Generated by Django 5.1.2 on 2024-11-04 11:58

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0002_alter_commission_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='photos/', variations={}),
        ),
    ]
