# Generated by Django 5.1.2 on 2024-11-05 11:07

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0003_alter_commission_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='photos/default.jpg', force_min_size=False, null=True, upload_to='photos/', variations={}),
        ),
    ]
