# Generated by Django 5.1.3 on 2024-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0005_submissiontowork'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontowork',
            name='formOfPresentation',
            field=models.CharField(choices=[('Exposicao', 'Exposição'), ('Painel', 'Painel'), ('Maquete', 'Maquete'), ('Outro', 'Outro')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissiontowork',
            name='formation',
            field=models.CharField(choices=[('EnsinoFundamental', 'Ensino Fundamental'), ('EnsinoMedio', 'Ensino Médio')], max_length=100),
        ),
    ]
