# Generated by Django 5.1.3 on 2024-12-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_participante_estado_and_more'),
        ('fecitec', '0009_alter_submissiontowork_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontowork',
            name='participante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.participante'),
            preserve_default=False,
        ),
    ]
