# Generated by Django 5.1.4 on 2024-12-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0010_submissiontowork_participante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiontowork',
            name='arquivo_panner',
        ),
    ]
