# Generated by Django 5.1.4 on 2024-12-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0011_remove_submissiontowork_arquivo_panner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissiontowork',
            old_name='formOfPresentation',
            new_name='form_of_presentation',
        ),
    ]
