# Generated by Django 5.1.2 on 2024-12-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0011_remove_submissiontowork_arquivo_panner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
