# Generated by Django 5.1.2 on 2024-12-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0012_delete_commission'),
        ('fecitec', '0012_rename_formofpresentation_submissiontowork_form_of_presentation'),
    ]

    operations = [
    ]
