# Generated by Django 5.1.2 on 2024-12-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fecitec', '0013_merge_20241210_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubmissionToWork',
        ),
    ]
